language: python

python:
  - "3.8"

services:
  - docker

jobs:
  include:
    - stage: build_and_test
      name: "Build"
      install: bin/build_base.sh
      
    - stage: build_and_test
      name: "Build and run test"
      install: bin/build_test.sh
      script: test.sh

