language: python

python:
  - "3.8"

cache: pip

services:
  - docker

jobs:
  include:
    - stage: build_and_test
      name: "Build"
      install: bin/build_base.sh
      # script: cd src && uvicorn main:app --host 0.0.0.0 --reload
      script: echo "BUILT SUCCESSFULY"
      
    - stage: build_and_test
      name: "Build and run test"
      install: bin/build_test.sh
      script: bin/test.sh

    - stage: deploy
      name: "Deploy"
      script: 
        - echo "NO DEPLOYEMENT YET"

